[package]
name = "rselisp"
version = "0.1.0"
authors = ["Richard Palethorpe <richiejp@f-m.fm>"]

[dependencies]
fnv = "*"
orbclient = "*"

[profile.bench]
opt-level = 3
debug = 2

[[bench]]
name = "perf"
path = "tests/perf.rs"
